ExiaSR/hyperion

api/config.py, api/settings.py, hyperion/models/user.py, hyperion/serializers.py, hyperion/tests/tests_serializers.py
add user and comment serializers && add corresponding tests (tests pass)
=> feat: add user and comment serializers

api/urls.py, hyperion/views/auth_views.py, hyperion/views/user_views.py
=> refactor: re-organize project structure

api/urls.py, hyperion/models/user.py, hyperion/serializers.py, hyperion/tests/tests_friend_views.py, hyperion/views/friend_views.py
Finished
1. GET /author/{author_id}/friends
2. POST /author/{author_id}/friends
3. GET /author/{author1_id}/friend/{service2}/author/{author2_id} 
4. POST /friendrequest 
5. GET /friendrequest 
6. PUT /friendrequest/{friendrequest_id}
Resolved User Story Issues
1. As an author, I want to know if I have friend requests
2. As an author, my server will know about my friends
Note:
1. Test passed (please check tests_friend_views if you need any detailed api instruction)
2. Only apply is_authenticated permission
3. Not very understand about the user story -- As an author, When I befriend someone it follows them, only when the other authors befriends me do I count as a real friend
TODO: we may need create some permissions for request from other server
=> feat: add friend views

hyperion/serializers.py, hyperion/tests/tests_serializers.py
style
- [Y ] My branch is up to date with `master`. [How?](https://github.com/ExiaSR/hyperion/wiki/How-to-collaborate)
- [ Y] Now it is a good time to ask for review.
=> fix: add username field to userprofile serializer

client/src/api.js, client/src/app.js, client/src/components/post-overlay.js, client/src/components/posts-stream.js, client/src/pages/home-page.js, client/src/stores/post-store.js
=> feat: posts can be opened with a permanent link

client/craco.config.js, client/package.json, client/src/api.js, client/src/components/app-layout.js, client/src/components/notification.js, client/src/hooks/index.js, client/src/hooks/use-interval.js, client/yarn.lock
=> feat: user can accept or reject friend request

hyperion/errors.py, hyperion/models/user.py, hyperion/tests/tests_friend_views.py, hyperion/views/friend_views.py
_[Duplicate friend request](https://github.com/ExiaSR/hyperion/issues/89)
不知道为啥我pycharm改了很多括号格式，
主要我改的地方
- add FriendAlreadyExist exception
- modified Friend.send_friend_request
- check request.user.id and firend.id
=> fix: friendrequest

api/urls.py, hyperion/serializers.py, hyperion/tests/tests_auth_views.py, hyperion/views/auth_views.py
_[Issue86](https://github.com/ExiaSR/hyperion/issues/86)
Note:
1. Not sure how to test, I still used conventional method which used self.client.login()
=> feat: add user registration endpoint

hyperion/serializers.py
=> fix: url in userprofile serializer

api/urls.py, client/package.json, client/src/api.js, client/src/stores/post-store.js, hyperion/views/post_views.py, requirements.txt
=> feat: user can delete their own posts

client/craco.config.js, client/src/api.js, client/src/app.js, client/src/components/private-route.js, client/src/pages/inactive-page.js, client/src/pages/login-page.scss, client/src/pages/not-found-page.js, client/src/pages/signup-page.js, client/src/stores/auth-store.js, client/src/utils/request.js
=> feat: user can create account

hyperion/views/friend_views.py
_[issue#99](https://github.com/ExiaSR/hyperion/issues/99)
- main change: line 250-254
=> fix: use requestuser.id to validate identify

hyperion/models/post.py, hyperion/serializers.py, hyperion/tests/tests_post.py
fix: post model can set post private to host friends only
=> fix: visible_to, in post serializer, is now a list of usernames

client/package.json, client/src/api.js, client/src/components/post-card.scss, client/src/components/posts-stream.js, client/src/components/profile-popover.js, client/yarn.lock
=> feat: author can friend local users

hyperion/admin.py
=> feat: add hyperion models to admin site

client/src/api.js, client/src/components/post-box.js, client/src/utils/request.js
=> feat: author can share private post to others

api/urls.py, hyperion/views/user_views.py
=> feat: add API to update author profile

client/src/stores/post-store.js
=> fix: posts are sorted with published field

hyperion/models/post.py, hyperion/serializers.py, hyperion/tests/tests_comment_api.py, hyperion/views/comment_views.py
=> fix: add comment API now follows spec

hyperion/tests/tests_user.py, hyperion/views/user_views.py
_[Issue#83](https://github.com/ExiaSR/hyperion/issues/83) related stories or create a new one if does not exist_
Note:
1. So far, it only can update bio, github, display_name, email
=> fix: profile update (backend side)

client/src/components/profile-popover.js
=> feat: show author bio in profile popover widget

hyperion/serializers.py, hyperion/tests/tests_comment_api.py, hyperion/views/comment_views.py
=> fix: add comment endpoint

hyperion/tests/tests_post_api.py, hyperion/views/post_views.py
=> feat: filtered all unlisted posts from stream

hyperion/views/post_views.py
=> fix: serveronly

hyperion/models/post.py, hyperion/views/post_views.py
=> fix: improve post retrieve post and not including SERVERONLY posts

api/settings.py, requirements.txt
=> fix: convert snake_case to camelCase

client/src/api.js, client/src/components/comment-box.js, client/src/components/post-overlay.js, client/src/components/posts-stream.js, client/src/stores/post-store.js
=> feat: author can post comment under posts

client/src/components/notification.js
#124 changed payload from snake_case to camelCase
=> fix: regression from #124

hyperion/models/post.py
=> fix: local user can't comment serveronly post

hyperion/models/user.py
when create user, the url will be added automatically. (before this commit, we only leave blank in url field, which will be hard for me to fetch profile by url)
之前创的user，我都手动加上url了
具体改的东西在def create_user_profile(sender, instance, created, **kwargs):下面
=> refactor: add url when create user

client/src/components/posts-stream.js
Some teams have not implemented comment yet. Add handling to this case.
=> fix: add handling when comments are not in post

api/urls.py, hyperion/models/post.py, hyperion/views/post_views.py
=> feat: add endpoint to fetch post belongs to a local user

hyperion/views/post_views.py
_[issue#141](https://github.com/ExiaSR/hyperion/issues/141) related stories or create a new one if does not exist_
- 我们url里的id都统一是User.id,不是UserProfile.id
- 后端的朋友再看看还有没有什么地方因为这个不统一产生的问题
- 大家看看自己写的views & serializer会不会因为这个受影响(UserProfileSerializer我已经检查是对的了）
=> fix: missused of user.id in post_view

hyperion/views/post_views.py
=> fix: get individual post now has visibility check

hyperion/views/post_views.py
if the request.user is local,
include foreign posts
if the request.user is a remote server,
don't
=> feat: include foreign public posts in /posts

hyperion/tests/tests_friend_views.py, hyperion/views/friend_views.py
_[Issue#147](https://github.com/ExiaSR/hyperion/issues/147) related stories or create a new one if does not exist_
=> fix: /author/{id}/friends

client/src/api.js, client/src/components/profile-popover.js, client/src/stores/post-store.js
Some foreign servers have stricter validation payload.
So we added to `displayName` to the payload as well.
=> fix: friendrequest is broken when adding foreign user

hyperion/views/post_views.py
=> fix: /api/posts only return public listed posts 

client/package.json, client/server.js, client/yarn.lock
=> chore: enable gzip in production deployment

api/urls.py, hyperion/views/post_views.py
=> feat: user can get individual foreign posts

hyperion/tests/tests_friend_views.py, hyperion/views/friend_views.py
=> fix: post friends author should be full id

.circleci/config.yml, api/config.py, api/urls.py, hyperion/views/post_views.py
CI test now spin up an internal Postgres DB instance
which improve the speed of unit testing by 500%
=> feat: get foreign posts for individual author

client/src/api.js, client/src/components/posts-stream.js, client/src/components/profile-popover.js, client/src/stores/post-store.js, client/src/utils/request.js
=> feat: fetch github events into posts stream

api/urls.py, hyperion/serializers.py, hyperion/views/post_views.py
=> feat: add endpoint to update an existed post

client/src/api.js, client/src/components/post-box.js, client/src/components/post-box.test.js, client/src/components/posts-stream.js, client/src/stores/index.js, client/src/stores/ui-store.js
=> feat: author can edit published posts

hyperion/views/post_views.py
#protips: don't trust the status code, payload could be flawed
=> fix: better error handling for foreign posts

hyperion/views/post_views.py
=> fix: mess up user.id and userprofile.id problem

hyperion/tests/tests_friend_views.py, hyperion/views/friend_views.py
=> fix: get friends list response standard

client/src/components/friend-list.js
=> fix: change author to authors according to API

hyperion/views/comment_views.py
=> fix: comment on foreign posts

hyperion/views/post_views.py
when current user id == author_id, user should be able to access all posts that he/she created
@Raymundo1
=> fix: for url author/author_id/posts

client/src/components/friend-card.js, client/src/components/friend-list.js
=> feat: add an indicator for external authors

hyperion/views/friend_views.py
=> fix: friend list api only return ID for server

hyperion/models/user.py, hyperion/tests/tests_comment_api.py, hyperion/tests/tests_post_api.py, hyperion/utils.py, hyperion/views/comment_views.py, hyperion/views/friend_views.py, hyperion/views/post_views.py
assumption: every server has consistent friendship
=> feat: add cross-server FOAF for everything

hyperion/views/post_views.py
Fixed a bug that even timeout occurs, still trying to read stuffs from response
=> fix: properly handle requests timeout exception

hyperion/serializers.py
=> fix: posts visibleTo field now returns user profile

hyperion/utils.py, hyperion/views/post_views.py, requirements.txt
=> perf: fetch foreign posts concurrently

client/src/pages/inactive-page.js
=> fix: inactive page now properly shows on mobile devices
